### ISSUE TITLE
[MBS] Adapt to React hydrate redraw of recording list

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#537]
New `div.recording-list` on top of `table.tbl`and (deferred?) redrawing(/`hydrate`?) of its content:

https://github.com/metabrainz/musicbrainz-server/commit/53fc7e3c18ff7fd4231cb1461ee58f01f29c0f2e#diff-8faa5353a1c84c9ee6dcf90be9bd62c669390f97c07ad8cf8401a8cee0bc7a6fR137-R140

```JavaScript
export default (hydrate<Props>(
  'div.recording-list',
  RecordingList,
): React.AbstractComponent<Props, void>);
```

This redraws the DOM at any time, thus wiping all what userscripts may have added.

Workaround
--------------------

One way to cope with that appears to be waiting for any `p.loading-message` to disappear, when DOM may be stable again.

For event listeners, [attach them to the body](https://github.com/jesus2099/konami-command/commit/10b884d9ce0d581440298eadbd44df2f6ffbb4be), instead.

Happens in:

- `/artist/<mbid>/recordings`
- `/recording/merge`

Sub-issues
---------------

### mb_COLLECTION-HIGHLIGHTER

- [x] Most highlights broken in merge page caused by recent React redraw #517

### mb_MERGE-HELPOR-2

- [x] Remove “Removed from merge” feature #497
- ~~Add AcoustID in MERGE HELPOR 2 for recordings merge #516~~
- [x] No more info on recording merge page #518
- [x] No more edit notes #535

### mb_SUPER-MIND-CONTROL-II-X-TURBO

- [x] Double click to submit merge does not trigger #550

**Comment by jesus2099** [comment]
Detach mb_MERGE-HELPOR-2 #516 as it’s a new feature request.
